# Generated by Django 4.1 on 2022-09-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[(1, 'Хирург'), (2, 'Терапевт')], max_length=30)),
                ('fullname', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiniorDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpo', models.IntegerField(unique=True)),
                ('employees', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[(1, 'Chui'), (2, 'Naryn'), (3, 'Issyk-Kul'), (4, 'Osh'), (5, 'Batken'), (6, 'Talas'), (7, 'Jalal-Abad')], max_length=20)),
                ('state', models.BooleanField(choices=[(1, 'Частная'), (2, 'Государственная')], default=True)),
                ('sinior_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.siniordoctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.patient'),
        ),
    ]
