# Generated by Django 4.1 on 2022-09-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_nurse_doctor_doctor_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(choices=[(1, 'Частная'), (2, 'Государственная')], default=True, max_length=20),
        ),
    ]
