# Generated by Django 4.1 on 2022-09-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_hospital_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(choices=[(1, 'Частная'), (2, 'Государственная')], max_length=20),
        ),
    ]
