# Generated by Django 4.1 on 2022-09-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_hospital_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='sinior_doctor',
        ),
    ]
