# Generated by Django 4.1 on 2022-09-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_hospital_sinior_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direction',
            field=models.IntegerField(choices=[(1, 'Хирург'), (2, 'Терапевт')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='region',
            field=models.IntegerField(choices=[(1, 'Chui'), (2, 'Naryn'), (3, 'Issyk-Kul'), (4, 'Osh'), (5, 'Batken'), (6, 'Talas'), (7, 'Jalal-Abad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.IntegerField(choices=[(1, 'Частная'), (2, 'Государственная')], max_length=20),
        ),
    ]
